name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: ./cicd/build.sh --push

      - name: Test
        run: ./cicd/test.sh
