name: Build and Test

on:
  pull_request:
    branches: 
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./cicd/build.sh --push

      - name: Test
        run: ./cicd/test.sh
