name: Data Pipeline

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  data_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update Data Locally
        run: ./cicd/etl.sh --env prod pynba_update

      - name: Sync to S3
        run: ./cicd/etl.sh --env prod pynba_sync

      - name: Upload Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: data_output
          path: data
